/******************************************************************************************************
File Name	: ultra_sonic.c
Author		: Sherif Beshr
Description : Source file for the ULTRASONIC driver
*******************************************************************************************************/

#include "std_types.h"
#include "ultrasonic.h"
#include "icu.h"
#include "gpio.h"
#include "util/delay.h"

/***************************************************************************************************
 *                                		Global Variables                                    	   *
 ***************************************************************************************************/

static volatile uint8 g_edge = 0;
static volatile uint16 g_timeHigh = 0;


/***************************************************************************************************
 *                                		Definitions                                  			   *
 ***************************************************************************************************/

/*
 * Description: Function to initialize ICU driver as required, setup the ICU callback function
 * and setup the direction for the trigger pin as output pin through the GPIO driver.
 */
void Ultrasonic_init(void)
{
	/*	Set the ICU configurations F_CPU and The Edge detection mode
	 *	Frequency = FCPU/8
	 *	Trigger: Rising edge
	 */
	Icu_ConfigType Icu_Config = { ULTRASONIC_FCPU, ULTRASONIC_EDGE_DETECTION };
	Icu_init(&Icu_Config);

	/* Setup the call back function pointer to ultrasonic driver:
	 * Ultrasonic_edgeProcessing
	 */
	Icu_setCallBack(Ultrasonic_edgeProcessing);

	/*Setup the direction for the trigger pin as output pin through the GPIO driver*/
	GPIO_setupPinDirection(ULTRASONIC_TRIGGER_PORT, ULTRASONIC_TRIGGER_PIN, PIN_OUTPUT);

	/*Initialize the pin value*/
	GPIO_writePin(ULTRASONIC_TRIGGER_PORT, ULTRASONIC_TRIGGER_PIN, LOGIC_LOW);
}

/*
 * Description: Function to send the trigger pulse to the ultra-sonic sensor.
 * At least send pulse (10us) --> Then the Ultra-sonic sensor automatically produces 8 (40KHz) pulses)
 */
void Ultrasonic_Trigger(void)
{
	GPIO_writePin(ULTRASONIC_TRIGGER_PORT, ULTRASONIC_TRIGGER_PIN, LOGIC_HIGH);
	_delay_us(10);
	GPIO_writePin(ULTRASONIC_TRIGGER_PORT, ULTRASONIC_TRIGGER_PIN, LOGIC_LOW);
}

/*
 * Description: Function to send the trigger pulse using Ultrasonic_Trigger function.
 * Then start measurements by the ICU from this moment.
 */
uint16 Ultrasonic_readDistance(void)
{
	uint16 distance;
	Ultrasonic_Trigger();
	while (g_edge == 0);
	/* distance = (speed of air * high time / 2) = ( 340[m/s] * high time / 2)
	 * Distance(cm) = 34000[cm/s] * Time /2 [ Time is in uS]
	 * 				= 17000[cm/s] * Time  = 17000 * Time * 1 * 1x10^-6
	 * 				= 0.017 * Time = Time / 58.8
	 */
	distance = ((float)(g_timeHigh)/58.8);
	g_timeHigh =0;
	return distance;
}

/*
 * Description: The Callback function that is called by the ICU driver.
 * It is used calculate the high time (pulse time) generated by the ultra-sonic sensor.
 */
void Ultrasonic_edgeProcessing(void)
{
	++g_edge;
	if (g_edge == 1)
	{
		/* Clear the counter timer register and start counting */
		Icu_clearTimerValue();
		/* Detect next falling edge */
		Icu_setEdgeDetectionType(FALLING);
	}
	else if (g_edge == 2)
	{
		/* Falling edge detected --> Store the timer counter register ( High Time )*/
		g_timeHigh = Icu_getInputCaptureValue();
		/* Detect next rising edge */
		Icu_setEdgeDetectionType(RISING);
		g_edge = 0;
	}
}
