/******************************************************************************************************
File Name	: ultrasonic.h
Author		: Sherif Beshr
Description : Header file for the ULTRASONIC driver
******************************************************************************************************/


#ifndef ULTRASONIC_H_
#define ULTRASONIC_H_

#include "std_types.h"

/***************************************************************************************************
 *                                		Definitions                                  			   *
 ***************************************************************************************************/

#define ULTRASONIC_TRIGGER_PORT					PORTB_ID
#define ULTRASONIC_TRIGGER_PIN					PIN5_ID

#define ULTRASONIC_FCPU							F_CPU_8
#define ULTRASONIC_EDGE_DETECTION				RISING

/***************************************************************************************************
 *                                		Function Prototypes                                  	   *
 ***************************************************************************************************/

/*
 * Description: Function to initialize ICU driver as required, setup the ICU callback function
 * and setup the direction for the trigger pin as output pin through the GPIO driver.
 */
void Ultrasonic_init(void);

/*
 * Description: Function to send the trigger pulse to the ultra-sonic sensor.
 */
void Ultrasonic_Trigger(void);

/*
 * Description: Function to send the trigger pulse using Ultrasonic_Trigger function.
 * Then start measurements by the ICU from this moment.
 */
uint16 Ultrasonic_readDistance(void);

/*
 * Description: The Callback function that is called by the ICU driver.
 * It is used calculate the high time (pulse time) generated by the ultra-sonic sensor.
 */
void Ultrasonic_edgeProcessing(void);

#endif /* ULTRASONIC_H_ */
